In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Source of Help: https://www.springboard.com/blog/beginners-guide-neural-network-in-python-scikit-learn-0-18/

In [3]:
import pandas as pd
df = pd.read_csv('starbucks-menu-nutrition-drinks.csv')

# First filter out those rows which 
# does not contain any data 

df = df.dropna(how = 'all') 

# only works if a cell is completely empty, in this case the cells are 'not empty' bc they have a dash ' - ' in them

In [4]:
df.head()

Unnamed: 0 Calories Fat (g)  \
0           Cool Lime Starbucks Refreshers™ Beverage       45       0   
1                                   Ombré Pink Drink        -       -   
2                                         Pink Drink        -       -   
3     Strawberry Acai Starbucks Refreshers™ Beverage       80       0   
4  Very Berry Hibiscus Starbucks Refreshers™ Beve...       60       0   

  Carb. (g) Fiber (g) Protein Sodium  
0        11         0       0     10  
1         -         -       -      -  
2         -         -       -      -  
3        18         1       0     10  
4        14         1       0     10

In [24]:
# i deleted rows that have missing info
df = df[df['Calories'] != '-']

In [29]:
df.shape

(92, 7)

In [7]:
list(df.columns)

['Unnamed: 0',
 'Calories',
 'Fat (g)',
 'Carb. (g)',
 'Fiber (g)',
 'Protein',
 'Sodium']

In [32]:
from sklearn.model_selection import train_test_split

In [34]:
X = df.drop('Unnamed: 0', axis=1)
y = df['Unnamed: 0']

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [37]:
from sklearn.neural_network import MLPClassifier

In [38]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [39]:
mlp.fit(X_train,y_train)

//anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
              learning_rate_init=0.001, max_iter=500, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [40]:
predictions = mlp.predict(X_test)

In [41]:
from sklearn.metrics import classification_report,confusion_matrix

In [42]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [43]:
print(classification_report(y_test,predictions))

                                                    precision    recall  f1-score   support

                                        Cappuccino       0.00      0.00      0.00       0.0
                              Cinnamon Dolce Crème       0.00      0.00      0.00       1.0
        Cinnamon Dolce Frappuccino® Blended Coffee       0.00      0.00      0.00       1.0
          Coffee Light Frappuccino® Blended Coffee       0.00      0.00      0.00       0.0
          Cool Lime Starbucks Refreshers™ Beverage       0.00      0.00      0.00       1.0
                                  Iced Caffè Latte       0.00      0.00      0.00       1.0
                                  Iced Caffè Mocha       0.00      0.00      0.00       1.0
                         Iced Cinnamon Dolce Latte       0.00      0.00      0.00       1.0
                                       Iced Coffee       0.00      0.00      0.00       1.0
        Iced Espresso Classics - Caramel Macchiato       0.00      0.00      0.

//anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
//anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
